'use client'
import { useMemo,useState } from 'react'
import Link from 'next/link'
import { Search, MapPin, BadgeCheck, Factory, Tags } from 'lucide-react'
import type { Provider } from '@/types/provider'
export default function Directory({providers}:{providers:Provider[]}){
 const [q,setQ]=useState(''); const [state,setState]=useState('Todos'); const [level,setLevel]=useState('Todos'); const [pl,setPl]=useState(false);
 const states=['Todos',...Array.from(new Set(providers.map(p=>p.estado))).sort()]
 const filtered=useMemo(()=>providers.filter(p=>{const hay=[p.nombre_comercial,p.ciudad,p.estado,p.tipo_proveedor,p.productos.join(' '),p.materiales.join(' ')].join(' ').toLowerCase(); return hay.includes(q.toLowerCase())&&(state==='Todos'||p.estado===state)&&(level==='Todos'||p.nivel===level)&&(!pl||p.private_label==='Sí')}),[q,state,level,pl,providers])
 return <><section className="border-b border-zinc-200 bg-sand"><div className="mx-auto max-w-7xl px-5 py-16"><div className="mb-4 inline-flex rounded-full border bg-white px-3 py-1 text-xs font-semibold text-wine">Investigación B2B · México 2026</div><h1 className="max-w-4xl text-4xl font-black tracking-tight md:text-6xl">Encuentra fabricantes y proveedores de bolsos en México</h1><p className="mt-5 max-w-3xl text-lg text-zinc-600">Fabricantes, maquiladores, talleres y mayoristas clasificados por capacidad, similitud de producto y nivel de confianza.</p><div className="mt-8 flex max-w-3xl items-center gap-3 rounded-2xl border bg-white px-4 py-3 shadow-sm"><Search className="text-zinc-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full outline-none" placeholder="Busca: bolsa tejida, León, private label, hobo..."/></div></div></section><main className="mx-auto max-w-7xl px-5 py-8"><div className="mb-6 flex flex-wrap gap-3"><select className="rounded-full border px-4 py-2" value={state} onChange={e=>setState(e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select><select className="rounded-full border px-4 py-2" value={level} onChange={e=>setLevel(e.target.value)}>{['Todos','A','B','C'].map(s=><option key={s}>{s}</option>)}</select><label className="flex items-center gap-2 rounded-full border bg-white px-4 py-2"><input type="checkbox" checked={pl} onChange={e=>setPl(e.target.checked)}/> Private label</label><span className="ml-auto self-center text-sm text-zinc-500">{filtered.length} resultados</span></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.sort((a,b)=>b.score-a.score).map(p=><article key={p.id} className="card p-6"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex gap-2"><span className="chip">Nivel {p.nivel}</span><span className="chip">{p.confianza}</span></div><h2 className="text-xl font-bold">{p.nombre_comercial}</h2><p className="mt-1 flex items-center gap-1 text-sm text-zinc-500"><MapPin size={14}/>{p.ciudad}, {p.estado}</p></div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-wine text-lg font-black text-white">{p.score}</div></div><p className="mt-4 text-sm leading-6 text-zinc-600">{p.motivo_recomendacion}</p><div className="mt-4 flex flex-wrap gap-2">{p.fabricacion_propia==='Sí'&&<span className="chip"><Factory size={12} className="inline"/> Fabrica</span>}{p.private_label==='Sí'&&<span className="chip"><BadgeCheck size={12} className="inline"/> Private label</span>}{p.productos.slice(0,2).map(x=><span className="chip" key={x}><Tags size={12} className="inline"/> {x}</span>)}</div><div className="mt-5 flex gap-2"><Link className="btn-primary" href={`/proveedores/${p.slug}`}>Ver proveedor</Link>{p.website&&<a className="btn-secondary" href={p.website} target="_blank">Sitio web</a>}</div></article>)}</div></main></>
}
